fruits_and_vegetables = [
    'apple',
    'banana',
    'beetroot',
    'bell pepper',
    'cabbage',
    'capsicum',
    'carrot',
    'cauliflower',
    'chilli pepper',
    'corn',
    'cucumber',
    'eggplant',
    'garlic',
    'ginger',
    'grapes',
    'jalepeno',
    'kiwi',
    'lemon',
    'lettuce',
    'mango',
    'onion',
    'orange',
    'paprika',
    'pear',
    'peas',
    'pineapple',
    'pomegranate',
    'potato',
    'radish',
    'soy beans',
    'spinach',
    'sweetcorn',
    'sweet potato',
    'tomato',
    'turnip',
    'watermelon'
]

fruit_condition = ['Raw Apple', 'Raw Banana', 'Raw Orange',
                   'Ripe Apple', 'Ripe Banana', 'Ripe Orange',
                   'Rotten Apple', 'Rotten Banana', 'Rotten Orange']
